name: CI
on: [push]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    env:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.KEY }}
        SSH_HOST: ${{ secrets.HOST }}
        SSH_PORT: ${{ secrets.PORT }}
        REPO: ${{ github.repository }}
    environment: mikrus
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host mikrus
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: List file
        run: ssh mikrus 'ls -al'
        
      - name: Make dir with repo name
        run: ssh mikrus 'mkdir $REPO'
