name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    environment: mikrus
    env:
        SSH_USER: '${{ secrets.USER }}'
        SSH_KEY: '${{ secrets.KEY }}'
        SSH_HOST: '${{ secrets.HOST }}'
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
            host: '${{ secrets.HOST }}'
            username: '${{ secrets.USERNAME }}'
            key: '${{ secrets.KEY }}'
            port: '${{ secrets.PORT }}'
            script: whoami
